version: '3.9'

networks:
  app_network:
    name: runtest
    driver: bridge

services:
  postman:
    container_name: postmanTests
    build:
      context: ./newman
      dockerfile: Dockerfile
    image: newman
    command:
      run "https://www.postman.com/collections/29800373-595b2c38-79f7-4fd2-bc40-f89df17be89e" -k \
      -e "reqres_env.json" \
      -r cli,json,htmlextra,allure \
      --reporter-json-export=".newman/reqres.in.json" \
      --reporter-htmlextra-export ./newman/index.html
    volumes:
      - ./docker_share:/etc/postman
    networks:
      - app_network
