version: '3.9'

networks:
  app_network:
    name: runtest
    driver: bridge

services:
  postman:
    container_name: postmanTests
    build:
      context: ./newman
      dockerfile: Dockerfile
    image: mynewman
    volumes:
      - /home/vit/ts_project/postman/docker_share:/srv/postman
    command:
      run "https://www.postman.com/collections/29800373-595b2c38-79f7-4fd2-bc40-f89df17be89e" -k \
      -e "reqres_env.json"
      -r cli,json,htmlextra,allure
      --reporter-json-export="/srv/postman/report.json"
      --reporter-htmlextra-export /srv/postman/index.html
      --reporter-allure-export /srv/postman/allure-results

    restart: no
    networks:
      - app_network
