version: '3.9'

# networks:
#   app_network:
#     name: runtest
#     driver: bridge

services:
  postman:
    image: vitgt/newman-htmlextra-allure
    container_name: postmanTests
    # build:
    #   context: ./newman
    #   dockerfile: Dockerfile
    # image: vitgt/newman-htmlextra-allure
    volumes:
      - ./shara:/etc/postman/
    command:
      newman run "https://www.postman.com/collections/29800373-595b2c38-79f7-4fd2-bc40-f89df17be89e" -k \
      -e "reqres_env.json"
      -r cli,json,htmlextra,allure
      --reporter-json-export="/etc/postman/report/report.json"
      --reporter-htmlextra-export /etc/postman/report/index-htmlextra.html
      --reporter-allure-export /etc/postman/allure-results
    # networks:
    #   - app_network

  allure:
    image: vitgt/allure-report
    container_name: allureTests


    volumes:
      - ./shara:/etc/allure/
    command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
    # command: /bin/sh -c "ls -la && allure generate allure-results --clean -o allure-report" && bin/sh
    # networks:
    #   - app_network

  # Allure запускается как сервер и не работает постоянно
  # allure:
  #   image: "frankescobar/allure-docker-service"
  #   environment:
  #     CHECK_RESULTS_EVERY_SECONDS: NONE
  #     KEEP_HISTORY: 1
  #     KEEP_HISTORY_LATEST: 25
  #   ports:
  #     - "5050:5050"
  #   volumes:
  #     - ${PWD}/docker_share/allure-results:/app/allure-results
  #     - ${PWD}/docker_share/default-reports:/app/default-reports
