version: '3.9'

networks:
  app_network:
    name: runtest
    driver: bridge

services:
  postman:
    container_name: postmanTests
    build:
      context: ./newman
      dockerfile: Dockerfile
      # env_file:
      # - "local.env"
      # args:
      #   USER_ID: ${USER_ID:-0}
      #   GROUP_ID: ${GROUP_ID:-0}
    image: mynewman
    volumes:
      # sudo chmod -R 777 ./docker_share
      - ${PWD}/docker_share:/srv/postman
    command:
      run "https://www.postman.com/collections/29800373-595b2c38-79f7-4fd2-bc40-f89df17be89e" -k \
      -e "reqres_env.json"
      -r cli,json,htmlextra,allure
      --reporter-json-export="/srv/postman/report.json"
      --reporter-htmlextra-export /srv/postman/index-htmlextra.html
      --reporter-allure-export /srv/postman/allure-results

    restart: no
    networks:
      - app_network
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/docker_share/allure-results:/app/allure-results
      - ${PWD}/docker_share/default-reports:/app/default-reports
