version: '3.9'

networks:
  app_network:
    name: runtest
    driver: bridge

services:
  postman:
    container_name: postmanTests
    build:
      context: ./newman
      dockerfile: Dockerfile
    image: postman
    volumes:
      - ${PWD}/shara:/opt/postman/
    command:
      run "https://www.postman.com/collections/29800373-595b2c38-79f7-4fd2-bc40-f89df17be89e" -k \
      -e "reqres_env.json"
      -r cli,json,htmlextra,allure
      --reporter-json-export="/opt/postman/report/report.json"
      --reporter-htmlextra-export /opt/postman/report/index-htmlextra.html
      --reporter-allure-export /opt/postman/allure-results
    restart: no
    networks:
      - app_network

  allure:
    depends_on:
      - postman
    container_name: allureTests
    build:
      context: ./allure
      dockerfile: Dockerfile
    image: allure
    volumes:
    - ${PWD}/shara:/opt/allure/
    command: /bin/sh -c "ls -la && allure generate --clean" && bin/sh
    restart: no
    networks:
      - app_network
