name: Postman_tests

on: [push, workflow_dispatch]

jobs:
  newman:
    runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@2
        - name: Run Neman via docker-compose
          run: |
            docker compose up --exit-code-from postman || true
        - name: Generate Allure report
            sudo docker compose run
        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            token: ${{ secrets.GHT_TOKEN }}
            branch: gh-pages
            folder: allure-report
            clean: true
