name: Postman_tests

on: workflow_dispatch
  # push:
  #   branches:
  #     - main  # Или другая ветка, в которой вы хотите выполнять тесты

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Newman via docker-compose
        uses: addnab/docker-run-action@v3
        with:
          image: vitgt/newman-htmlextra-allure:latest
          options:
            -v ${{ github.workspace}}/shara:/etc/postman
          run: |
            newman run "https://www.postman.com/collections/29800373-595b2c38-79f7-4fd2-bc40-f89df17be89e" -k \
            -e "reqres_env.json" \
            -r cli,allure \
      - name: Generate Allure report
        uses: addnab/docker-run-action@v3
        with:
          image: vitgt/allure-report
          options:
            -v ${{ github.workspace}}/shara:/etc/allure
          run: |
            allure generate
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GHT_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
