name: Postman_tests

on:
  push:
    branches:
      - main  # Или другая ветка, в которой вы хотите выполнять тесты

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Newman via docker-compose
        run: |
          docker compose up --exit-code-from postman || true

      - name: Generate Allure report
        run: |
          sudo docker compose run allure

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GHT_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
